# bat Tokyo Night themes
# Source: https://github.com/folke/tokyonight.nvim/tree/main/extras/sublime
[".config/bat/themes/tokyonight_day.tmTheme"]
type = "file"
url = "https://raw.githubusercontent.com/folke/tokyonight.nvim/main/extras/sublime/tokyonight_day.tmTheme"
refreshPeriod = "168h"

[".config/bat/themes/tokyonight_moon.tmTheme"]
type = "file"
url = "https://raw.githubusercontent.com/folke/tokyonight.nvim/main/extras/sublime/tokyonight_moon.tmTheme"
refreshPeriod = "168h"

[".config/bat/themes/tokyonight_night.tmTheme"]
type = "file"
url = "https://raw.githubusercontent.com/folke/tokyonight.nvim/main/extras/sublime/tokyonight_night.tmTheme"
refreshPeriod = "168h"

[".config/bat/themes/tokyonight_storm.tmTheme"]
type = "file"
url = "https://raw.githubusercontent.com/folke/tokyonight.nvim/main/extras/sublime/tokyonight_storm.tmTheme"
refreshPeriod = "168h"
