# Yazi keymap configuration
# See: https://yazi-rs.github.io/docs/configuration/keymap

[mgr]
prepend_keymap = [
    { on = "<C-p>", run = "plugin toggle-pane max-preview", desc = "Toggle max preview" },
]
